const express=require('express');const cors=require('cors');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const crypto=require('crypto');const {Pool}=require('pg');const XLSX=require('xlsx');const PDFDocument=require('pdfkit');
const app=express();app.use(cors());app.use(express.json({limit:'2mb'}));
const PORT=process.env.PORT||5000, JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_IN_RENDER', FRONTEND_URL=process.env.FRONTEND_URL||'*';
if(!process.env.DATABASE_URL) console.warn('DATABASE_URL is not set. Production deployment requires Supabase PostgreSQL.');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const uid=p=>`${p}_${crypto.randomBytes(7).toString('hex')}`;
async function q(text,params=[]){return (await pool.query(text,params)).rows}
async function init(){
 await q(`CREATE TABLE IF NOT EXISTS users(id text primary key,username text unique not null,name text not null,role text not null check(role in ('admin','manager')),password_hash text not null,active boolean not null default true,created_at timestamptz not null default now())`);
 await q(`CREATE TABLE IF NOT EXISTS warehouses(id text primary key,name text unique not null,location text,capacity numeric not null default 0,created_at timestamptz not null default now())`);
 await q(`CREATE TABLE IF NOT EXISTS suppliers(id text primary key,name text unique not null,email text,phone text,address text,outstanding_balance numeric not null default 0,created_at timestamptz not null default now())`);
 await q(`CREATE TABLE IF NOT EXISTS products(id text primary key,sku text unique not null,barcode text,name text not null,brand text,category text,unit text not null default 'pcs',purchase_price numeric not null default 0,selling_price numeric not null default 0,current_stock numeric not null default 0,min_stock numeric not null default 0,warehouse_id text references warehouses(id) on delete set null,supplier_id text references suppliers(id) on delete set null,client_name text,status text not null default 'Available',created_at timestamptz not null default now(),updated_at timestamptz not null default now())`);
 await q(`CREATE TABLE IF NOT EXISTS transactions(id text primary key,product_id text references products(id) on delete set null,user_id text references users(id) on delete set null,type text not null,quantity numeric not null,unit_cost numeric not null default 0,selling_price numeric not null default 0,client_name text,note text,previous_stock numeric not null,new_stock numeric not null,warehouse_id text references warehouses(id) on delete set null,created_at timestamptz not null default now())`);
 await q(`CREATE TABLE IF NOT EXISTS notifications(id text primary key,user_id text references users(id) on delete cascade,title text not null,message text not null,severity text not null default 'low',activity_id text,read_at timestamptz,created_at timestamptz not null default now(),deleted_at timestamptz)`);
 await q(`CREATE TABLE IF NOT EXISTS activity_logs(id text primary key,user_id text references users(id) on delete set null,action text not null,entity_type text,entity_id text,created_at timestamptz not null default now())`);
 await q(`CREATE TABLE IF NOT EXISTS reports(id text primary key,title text not null,created_by text references users(id) on delete set null,start_date date,end_date date,notes text,created_at timestamptz not null default now())`);
 await q(`CREATE INDEX IF NOT EXISTS idx_tx_created ON transactions(created_at);CREATE INDEX IF NOT EXISTS idx_notif_user ON notifications(user_id,created_at);CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_logs(created_at)`);
 const admins=await q('SELECT id FROM users WHERE role=$1 LIMIT 1',['admin']);if(!admins.length){const username=process.env.ADMIN_USERNAME||'admin',password=process.env.ADMIN_PASSWORD||'ChangeMe_123!',name=process.env.ADMIN_NAME||'Administrator';await q('INSERT INTO users(id,username,name,role,password_hash) VALUES($1,$2,$3,$4,$5)',[uid('usr'),username,name,'admin',bcrypt.hashSync(password,12)]);console.log(`Initial admin created: ${username}`);}
}
function auth(req,res,next){const h=req.headers.authorization||'';try{if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:'Authentication required'})}}
function role(...roles){return(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Admin permission required'})}
async function activity(userId,action,type,id){const aid=uid('act');await q('INSERT INTO activity_logs(id,user_id,action,entity_type,entity_id) VALUES($1,$2,$3,$4,$5)',[aid,userId,action,type||null,id||null]);const others=await q('SELECT id FROM users WHERE active=true AND id<>$1',[userId]);for(const u of others)await q('INSERT INTO notifications(id,user_id,title,message,severity,activity_id) VALUES($1,$2,$3,$4,$5,$6)',[uid('not'),u.id,'Inventory activity',action,'low',aid]);return aid}
async function lowStock(product,userId){if(Number(product.current_stock)<=Number(product.min_stock)){const users=await q("SELECT id FROM users WHERE active=true AND role IN ('admin','manager')");for(const u of users)await q('INSERT INTO notifications(id,user_id,title,message,severity) VALUES($1,$2,$3,$4,$5)',[uid('not'),u.id,'Low stock warning',`${product.name} (${product.sku}) has ${product.current_stock} ${product.unit} remaining. Minimum is ${product.min_stock}.`,'high']);}}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'inventory',database:!!process.env.DATABASE_URL}));
app.post('/api/auth/login',async(req,res)=>{try{const u=(await q('SELECT * FROM users WHERE username=$1 AND active=true',[req.body.username]))[0];if(!u||!bcrypt.compareSync(req.body.password||'',u.password_hash))return res.status(401).json({error:'Invalid username or password'});const user={id:u.id,username:u.username,name:u.name,role:u.role};const token=jwt.sign(user,JWT_SECRET,{expiresIn:'12h'});await activity(u.id,`${u.name} logged in`,'auth',u.id);res.json({token,user})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/me',auth,async(req,res)=>res.json(req.user));
app.get('/api/users',auth,role('admin'),async(req,res)=>res.json(await q('SELECT id,username,name,role,active,created_at FROM users ORDER BY created_at')));
app.post('/api/users',auth,role('admin'),async(req,res)=>{try{const {username,name,role:r,password}=req.body;if(!username||!name||!password||!['admin','manager'].includes(r))return res.status(400).json({error:'username, name, role and password are required'});const id=uid('usr');await q('INSERT INTO users(id,username,name,role,password_hash) VALUES($1,$2,$3,$4,$5)',[id,username,name,r,bcrypt.hashSync(password,12)]);await activity(req.user.id,`${req.user.name} created user ${username}`,'user',id);res.json({id,username,name,role:r})}catch(e){res.status(400).json({error:e.code==='23505'?'Username already exists':e.message})}});
app.delete('/api/users/:id',auth,role('admin'),async(req,res)=>{if(req.params.id===req.user.id)return res.status(400).json({error:'You cannot delete your own account'});await q('UPDATE users SET active=false WHERE id=$1',[req.params.id]);await activity(req.user.id,`${req.user.name} disabled a user`,'user',req.params.id);res.json({ok:true})});
app.get('/api/warehouses',auth,async(req,res)=>res.json(await q('SELECT * FROM warehouses ORDER BY name')));
app.post('/api/warehouses',auth,role('admin','manager'),async(req,res)=>{try{const id=uid('wh');await q('INSERT INTO warehouses(id,name,location,capacity) VALUES($1,$2,$3,$4)',[id,req.body.name,req.body.location||'',Number(req.body.capacity)||0]);await activity(req.user.id,`${req.user.name} added warehouse ${req.body.name}`,'warehouse',id);res.json({id})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/warehouses/:id',auth,role('admin','manager'),async(req,res)=>{try{await q('UPDATE warehouses SET name=$1,location=$2,capacity=$3 WHERE id=$4',[req.body.name,req.body.location||'',Number(req.body.capacity)||0,req.params.id]);await activity(req.user.id,`${req.user.name} edited a warehouse`,'warehouse',req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/warehouses/:id',auth,role('admin'),async(req,res)=>{await q('DELETE FROM warehouses WHERE id=$1',[req.params.id]);await activity(req.user.id,`${req.user.name} deleted a warehouse`,'warehouse',req.params.id);res.json({ok:true})});
app.post('/api/warehouses/bulk',auth,role('admin','manager'),async(req,res)=>{const rows=Array.isArray(req.body.items)?req.body.items:[];for(const w of rows)await q('INSERT INTO warehouses(id,name,location,capacity) VALUES($1,$2,$3,$4) ON CONFLICT(name) DO NOTHING',[uid('wh'),w.name,w.location||'',Number(w.capacity)||0]);await activity(req.user.id,`${req.user.name} bulk-added ${rows.length} warehouses`,'warehouse',null);res.json({count:rows.length})});
app.delete('/api/warehouses/bulk',auth,role('admin'),async(req,res)=>{const ids=req.body.ids||[];await q('DELETE FROM warehouses WHERE id=ANY($1::text[])',[ids]);await activity(req.user.id,`${req.user.name} bulk-deleted warehouses`,'warehouse',null);res.json({ok:true})});
app.get('/api/suppliers',auth,async(req,res)=>res.json(await q('SELECT * FROM suppliers ORDER BY name')));
app.post('/api/suppliers',auth,role('admin','manager'),async(req,res)=>{try{const id=uid('sup');await q('INSERT INTO suppliers(id,name,email,phone,address,outstanding_balance) VALUES($1,$2,$3,$4,$5,$6)',[id,req.body.name,req.body.email||'',req.body.phone||'',req.body.address||'',Number(req.body.outstandingBalance)||0]);await activity(req.user.id,`${req.user.name} added supplier ${req.body.name}`,'supplier',id);res.json({id})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/suppliers/:id',auth,role('admin','manager'),async(req,res)=>{try{await q('UPDATE suppliers SET name=$1,email=$2,phone=$3,address=$4,outstanding_balance=$5 WHERE id=$6',[req.body.name,req.body.email||'',req.body.phone||'',req.body.address||'',Number(req.body.outstandingBalance)||0,req.params.id]);await activity(req.user.id,`${req.user.name} edited a supplier`,'supplier',req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/suppliers/:id',auth,role('admin'),async(req,res)=>{await q('DELETE FROM suppliers WHERE id=$1',[req.params.id]);await activity(req.user.id,`${req.user.name} deleted a supplier`,'supplier',req.params.id);res.json({ok:true})});
app.post('/api/suppliers/bulk',auth,role('admin','manager'),async(req,res)=>{const rows=req.body.items||[];for(const s of rows)await q('INSERT INTO suppliers(id,name,email,phone,address,outstanding_balance) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(name) DO NOTHING',[uid('sup'),s.name,s.email||'',s.phone||'',s.address||'',Number(s.outstandingBalance)||0]);await activity(req.user.id,`${req.user.name} bulk-added ${rows.length} suppliers`,'supplier',null);res.json({count:rows.length})});
app.delete('/api/suppliers/bulk',auth,role('admin'),async(req,res)=>{await q('DELETE FROM suppliers WHERE id=ANY($1::text[])',[req.body.ids||[]]);await activity(req.user.id,`${req.user.name} bulk-deleted suppliers`,'supplier',null);res.json({ok:true})});
app.get('/api/products',auth,async(req,res)=>{let sql=`SELECT p.*,w.name warehouse_name,s.name supplier_name FROM products p LEFT JOIN warehouses w ON w.id=p.warehouse_id LEFT JOIN suppliers s ON s.id=p.supplier_id WHERE 1=1`,a=[];if(req.query.search){a.push(`%${req.query.search}%`);sql+=` AND (p.name ILIKE $${a.length} OR p.sku ILIKE $${a.length} OR COALESCE(p.barcode,'') ILIKE $${a.length})`}if(req.query.status){a.push(req.query.status);sql+=` AND p.status=$${a.length}`}sql+=' ORDER BY p.created_at DESC';res.json(await q(sql,a))});
app.post('/api/products',auth,role('admin','manager'),async(req,res)=>{try{const p=req.body,id=uid('prod');const stock=Number(p.currentStock)||0;await q(`INSERT INTO products(id,sku,barcode,name,brand,category,unit,purchase_price,selling_price,current_stock,min_stock,warehouse_id,supplier_id,client_name,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[id,p.sku,p.barcode||'',p.name,p.brand||'',p.category||'',p.unit||'pcs',Number(p.purchasePrice)||0,Number(p.sellingPrice)||0,stock,Number(p.minStock)||0,p.warehouseId||null,p.supplierId||null,p.clientName||null,stock<=0?'Out of Stock':stock<=Number(p.minStock)?'Low Stock':'Available']);if(stock)await q('INSERT INTO transactions(id,product_id,user_id,type,quantity,unit_cost,selling_price,previous_stock,new_stock,warehouse_id,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[uid('tx'),id,req.user.id,'stock-in',stock,Number(p.purchasePrice)||0,Number(p.sellingPrice)||0,0,stock,p.warehouseId||null,'Initial stock']);await activity(req.user.id,`${req.user.name} added product ${p.name}`,'product',id);const product=(await q('SELECT * FROM products WHERE id=$1',[id]))[0];await lowStock(product,req.user.id);res.json(product)}catch(e){res.status(400).json({error:e.code==='23505'?'SKU already exists':e.message})}});
app.put('/api/products/:id',auth,role('admin','manager'),async(req,res)=>{try{const p=req.body;await q(`UPDATE products SET sku=$1,barcode=$2,name=$3,brand=$4,category=$5,unit=$6,purchase_price=$7,selling_price=$8,min_stock=$9,warehouse_id=$10,supplier_id=$11,client_name=$12,updated_at=now(),status=CASE WHEN current_stock<=0 THEN 'Out of Stock' WHEN current_stock<= $9 THEN 'Low Stock' ELSE 'Available' END WHERE id=$13`,[p.sku,p.barcode||'',p.name,p.brand||'',p.category||'',p.unit||'pcs',Number(p.purchasePrice)||0,Number(p.sellingPrice)||0,Number(p.minStock)||0,p.warehouseId||null,p.supplierId||null,p.clientName||null,req.params.id]);await activity(req.user.id,`${req.user.name} edited product ${p.name||req.params.id}`,'product',req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/products/:id',auth,role('admin'),async(req,res)=>{await q('DELETE FROM products WHERE id=$1',[req.params.id]);await activity(req.user.id,`${req.user.name} deleted a product`,'product',req.params.id);res.json({ok:true})});
app.post('/api/products/bulk-delete',auth,role('admin'),async(req,res)=>{await q('DELETE FROM products WHERE id=ANY($1::text[])',[req.body.ids||[]]);await activity(req.user.id,`${req.user.name} bulk-deleted products`,'product',null);res.json({ok:true})});
app.post('/api/inventory/:id/:action',auth,role('admin','manager'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const p=(await client.query('SELECT * FROM products WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!p)throw new Error('Product not found');const action=req.params.action,qty=Number(req.body.quantity);if(!Number.isFinite(qty)||qty<=0)throw new Error('Quantity must be greater than zero');let delta=0,type=action; if(action==='stock-in'||action==='return')delta=qty;if(['stock-out','damage'].includes(action))delta=-qty;if(action==='transfer')delta=0;if(delta<0&&Number(p.current_stock)+delta<0)throw new Error(`Insufficient stock. Available: ${p.current_stock}, requested: ${qty}`);const prev=Number(p.current_stock),next=prev+delta;let sell=Number(req.body.sellingPrice)||Number(p.selling_price),cost=Number(req.body.unitCost)||Number(p.purchase_price);if(action==='stock-out'){if(req.body.sellingPrice!=null)sell=Number(req.body.sellingPrice);await client.query('UPDATE products SET client_name=$1,selling_price=$2 WHERE id=$3',[req.body.clientName||null,sell,p.id]);}
 if(action==='transfer'){if(!req.body.toWarehouseId)throw new Error('Destination warehouse required');await client.query('UPDATE products SET warehouse_id=$1,updated_at=now() WHERE id=$2',[req.body.toWarehouseId,p.id]);}
 await client.query(`UPDATE products SET current_stock=$1,status=CASE WHEN $1<=0 THEN 'Out of Stock' WHEN $1<=min_stock THEN 'Low Stock' ELSE 'Available' END,updated_at=now() WHERE id=$2`,[next,p.id]);await client.query(`INSERT INTO transactions(id,product_id,user_id,type,quantity,unit_cost,selling_price,client_name,note,previous_stock,new_stock,warehouse_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[uid('tx'),p.id,req.user.id,type,qty,cost,sell,req.body.clientName||null,req.body.note||'',prev,next,req.body.toWarehouseId||p.warehouse_id||null]);await client.query('COMMIT');const updated=(await q('SELECT * FROM products WHERE id=$1',[p.id]))[0];await activity(req.user.id,`${req.user.name} recorded ${type} of ${qty} ${p.unit} for ${p.name}`,'transaction',p.id);await lowStock(updated,req.user.id);res.json(updated)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/transactions',auth,async(req,res)=>{let sql=`SELECT t.*,p.name product_name,p.sku,u.name user_name FROM transactions t LEFT JOIN products p ON p.id=t.product_id LEFT JOIN users u ON u.id=t.user_id WHERE 1=1`,a=[];if(req.query.start){a.push(req.query.start);sql+=` AND t.created_at >= $${a.length}::date`}if(req.query.end){a.push(req.query.end);sql+=` AND t.created_at < ($${a.length}::date + interval '1 day')`}sql+=' ORDER BY t.created_at DESC LIMIT 2000';res.json(await q(sql,a))});
app.get('/api/activity-logs',auth,async(req,res)=>res.json(await q(`SELECT a.*,u.name user_name FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 1000`)));
app.get('/api/notifications',auth,async(req,res)=>{await q(`UPDATE notifications SET read_at=now() WHERE user_id=$1 AND read_at IS NULL AND created_at < now() - interval '24 hours'`,[req.user.id]);res.json(await q(`SELECT * FROM notifications WHERE user_id=$1 AND deleted_at IS NULL AND created_at >= now()-interval '24 hours' ORDER BY created_at DESC`,[req.user.id]))});
app.put('/api/notifications/:id/read',auth,async(req,res)=>{await q('UPDATE notifications SET read_at=now() WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});
app.delete('/api/notifications/:id',auth,async(req,res)=>{await q('UPDATE notifications SET deleted_at=now() WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});
app.post('/api/notifications/bulk-delete',auth,async(req,res)=>{await q('UPDATE notifications SET deleted_at=now() WHERE user_id=$1 AND id=ANY($2::text[])',[req.user.id,req.body.ids||[]]);res.json({ok:true})});
function dates(req){return [req.query.start||null,req.query.end||null]}
async function reportRows(start,end){let where='';const a=[];if(start){a.push(start);where+=` AND t.created_at >= $${a.length}::date`}if(end){a.push(end);where+=` AND t.created_at < ($${a.length}::date + interval '1 day')`}return q(`SELECT t.created_at,t.type,p.sku,p.name,p.category,t.quantity,t.unit_cost,t.selling_price,t.client_name,t.previous_stock,t.new_stock,u.name user_name,s.name supplier_name FROM transactions t LEFT JOIN products p ON p.id=t.product_id LEFT JOIN users u ON u.id=t.user_id LEFT JOIN suppliers s ON s.id=p.supplier_id WHERE 1=1 ${where} ORDER BY t.created_at DESC`,a)}
function csv(rows){if(!rows.length)return '';const keys=Object.keys(rows[0]);const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return [keys.join(','),...rows.map(r=>keys.map(k=>esc(r[k])).join(','))].join('\n')}
function exportRows(rows,format,res,name){if(format==='csv'){res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition',`attachment; filename=${name}.csv`);return res.send(csv(rows))}if(format==='xlsx'){const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Report');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename=${name}.xlsx`);return res.send(buf)}const doc=new PDFDocument({margin:30,size:'A4',layout:'landscape'});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename=${name}.pdf`);doc.pipe(res);doc.fontSize(18).text('Inventory Report');doc.moveDown();doc.fontSize(8);rows.slice(0,1000).forEach(r=>doc.text(Object.entries(r).map(([k,v])=>`${k}: ${v??''}`).join(' | ')));doc.end()}
app.get('/api/reports/inventory.:format',auth,async(req,res)=>{try{const rows=await reportRows(...dates(req));exportRows(rows,req.params.format,res,'inventory-report')}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/reports/overall.:format',auth,async(req,res)=>{try{const rows=await reportRows(...dates(req));exportRows(rows,req.params.format,res,'overall-report')}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/reports',auth,async(req,res)=>{const id=uid('rep');await q('INSERT INTO reports(id,title,created_by,start_date,end_date,notes) VALUES($1,$2,$3,$4,$5,$6)',[id,req.body.title||'Inventory Report',req.user.id,req.body.startDate||null,req.body.endDate||null,req.body.notes||'']);await activity(req.user.id,`${req.user.name} created report ${req.body.title||'Inventory Report'}`,'report',id);res.json({id})});
app.get('/api/reports',auth,async(req,res)=>res.json(await q(`SELECT r.*,u.name created_by_name FROM reports r LEFT JOIN users u ON u.id=r.created_by ORDER BY r.created_at DESC`)));
app.get('/api/dashboard',auth,async(req,res)=>{const start=req.query.start||null,end=req.query.end||null;let cond='';const a=[];if(start){a.push(start);cond+=` AND created_at >= $${a.length}::date`}if(end){a.push(end);cond+=` AND created_at < ($${a.length}::date + interval '1 day')`}const totals=(await q(`SELECT COALESCE(SUM(current_stock),0) total_stock,COALESCE(SUM(current_stock*purchase_price),0) inventory_value,COUNT(*) products,COUNT(*) FILTER(WHERE current_stock<=min_stock) low_stock FROM products`))[0];const sales=(await q(`SELECT COALESCE(SUM(quantity),0) qty,COALESCE(SUM(quantity*selling_price),0) revenue,COALESCE(SUM(quantity*(selling_price-unit_cost)),0) profit FROM transactions WHERE type='stock-out' ${cond}`,a))[0];const movement=await q(`SELECT date_trunc('day',created_at) day,type,COALESCE(SUM(quantity),0) quantity FROM transactions WHERE 1=1 ${cond} GROUP BY 1,type ORDER BY 1`,a);const cats=await q('SELECT category,COALESCE(SUM(current_stock),0) stock FROM products GROUP BY category ORDER BY stock DESC');const forecast=await q(`SELECT p.id,p.name,p.sku,p.current_stock,p.min_stock,COALESCE(s.weekly,0) weekly_sales,CASE WHEN COALESCE(s.weekly,0)>0 THEN ROUND((p.current_stock/s.weekly)::numeric,1) END days_estimate FROM products p LEFT JOIN (SELECT product_id,SUM(quantity)/GREATEST(1,EXTRACT(epoch FROM (now()-MIN(created_at)) / 604800)) weekly FROM transactions WHERE type='stock-out' GROUP BY product_id) s ON s.product_id=p.id ORDER BY CASE WHEN COALESCE(s.weekly,0)>0 THEN p.current_stock/s.weekly ELSE 999999 END LIMIT 10`);res.json({totals,sales,movement,categories:cats,forecast,range:{start,end}})});
app.get('/api/forecast',auth,async(req,res)=>{res.json(await q(`SELECT p.name,p.sku,p.current_stock,p.min_stock,COALESCE(s.weekly_sales,0) weekly_sales,CASE WHEN COALESCE(s.weekly_sales,0)>0 THEN ROUND((p.current_stock/s.weekly_sales)::numeric,1) ELSE NULL END days_to_stockout FROM products p LEFT JOIN (SELECT product_id,SUM(quantity)/GREATEST(1,EXTRACT(epoch FROM (now()-MIN(created_at))/604800)) weekly_sales FROM transactions WHERE type='stock-out' GROUP BY product_id) s ON s.product_id=p.id ORDER BY CASE WHEN COALESCE(s.weekly_sales,0)>0 THEN p.current_stock/s.weekly_sales ELSE 999999 END LIMIT 20`))});
app.use(express.static(__dirname));app.get('*',(req,res)=>res.sendFile(require('path').join(__dirname,'index.html')));
init().then(()=>app.listen(PORT,()=>console.log(`Inventory server listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
